# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         
url:                 https://lanyon.getpoole.com
baseurl:             'http://architgupta.github.io/lanyon/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Archit Gupta
  url:               test
  email:             test@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
